ALTER TABLE mosques
  ADD COLUMN IF NOT EXISTS image_url TEXT,
  ADD COLUMN IF NOT EXISTS sect VARCHAR(80) NOT NULL DEFAULT 'Community',
  ADD COLUMN IF NOT EXISTS contact_name VARCHAR(160),
  ADD COLUMN IF NOT EXISTS contact_phone VARCHAR(40),
  ADD COLUMN IF NOT EXISTS contact_email CITEXT,
  ADD COLUMN IF NOT EXISTS website_url TEXT,
  ADD COLUMN IF NOT EXISTS duhr_time VARCHAR(32),
  ADD COLUMN IF NOT EXISTS asr_time VARCHAR(32);
